export {default as Component} from './component'
export { default as Icons } from './icon'
//export {default as Map} from './map'
export {default as Bundle} from './bundler'
export {default as Video} from './video'
export {default as FlyWeight} from './flyWeight'
export {default as GlobalTooltip} from './globalTooltip'
export {default as Chart} from './echart'
export {default as Dialog} from './dialog'
export {default as Map} from './map'
export {default as DynamicComponent} from './dynamic-component'